server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: ZtQfBMQkaFwBzWDG
  data:
    redis:
      lettuce:
        pool:
          min-idle: 0
          max-active: 8
          max-idle: 8
          max-wait: 300ms
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms
      password: 20040902zank
logging:
  file:
    name: ./logs/big_event_runtime.log
  pattern:
    # 控制台输出格式
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    # log文件输出格式
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"